development:
  adapter: postgresql
  database: capacitor_dev
  host: localhost

production:
  adapter: postgresql
  database: capacitor_prod
  host: localhost

test:
  adapter: postgresql
  database: capacitor_test
  host: localhost

